#pragma once

#include "NeuralNet_global.h"
#include <string>

#ifdef _DEBUG
//#define NEURAL_NET_3_PROFILING
#endif

// Profiling
#ifdef NEURAL_NET_3_PROFILING
	#include <easy/profiler.h>

	#define NNP_BLOCK(text, color) EASY_BLOCK(text, profiler::colors:: color)
	#define NNP_END_BLOCK EASY_END_BLOCK
	#define NNP_FUNCTION(color) EASY_FUNCTION(profiler::colors:: color)
	#define NNP_THREAD(name) EASY_THREAD(name)
#else
	#define NNP_BLOCK(text, color)
	#define NNP_END_BLOCK
	#define NNP_FUNCTION(color)
	#define NNP_THREAD(name)
#endif
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)

// Different color stages
#define NNP_COLOR_STAGE_1 50
#define NNP_COLOR_STAGE_2 100
#define NNP_COLOR_STAGE_3 200
#define NNP_COLOR_STAGE_4 300
#define NNP_COLOR_STAGE_5 400
#define NNP_COLOR_STAGE_6 500
#define NNP_COLOR_STAGE_7 600
#define NNP_COLOR_STAGE_8 700
#define NNP_COLOR_STAGE_9 800
#define NNP_COLOR_STAGE_10 900
#define NNP_COLOR_STAGE_11 A100 
#define NNP_COLOR_STAGE_12 A200 
#define NNP_COLOR_STAGE_13 A400 
#define NNP_COLOR_STAGE_14 A700 

/*
// Colors for Canvas 
#define NNP_CANVAS_COLORBASE Green
#define NNP_CANVAS_COLOR_1  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_1 )
#define NNP_CANVAS_COLOR_2  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_2 )
#define NNP_CANVAS_COLOR_3  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_3 )
#define NNP_CANVAS_COLOR_4  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_4 )
#define NNP_CANVAS_COLOR_5  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_5 )
#define NNP_CANVAS_COLOR_6  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_6 )
#define NNP_CANVAS_COLOR_7  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_7 )
#define NNP_CANVAS_COLOR_8  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_8 )
#define NNP_CANVAS_COLOR_9  CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_9 )
#define NNP_CANVAS_COLOR_10 CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_10)
#define NNP_CANVAS_COLOR_11 CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_11) 
#define NNP_CANVAS_COLOR_12 CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_12) 
#define NNP_CANVAS_COLOR_13 CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_13) 
#define NNP_CANVAS_COLOR_14 CONCAT_SYMBOLS(NNP_CANVAS_COLORBASE , NNP_COLOR_STAGE_14) 

// Colors for CanvasContainer
#define NNP_CANVASCONTAINER_COLORBASE LightGreen
#define NNP_CANVASCONTAINER_COLOR_1  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_1 )
#define NNP_CANVASCONTAINER_COLOR_2  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_2 )
#define NNP_CANVASCONTAINER_COLOR_3  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_3 )
#define NNP_CANVASCONTAINER_COLOR_4  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_4 )
#define NNP_CANVASCONTAINER_COLOR_5  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_5 )
#define NNP_CANVASCONTAINER_COLOR_6  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_6 )
#define NNP_CANVASCONTAINER_COLOR_7  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_7 )
#define NNP_CANVASCONTAINER_COLOR_8  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_8 )
#define NNP_CANVASCONTAINER_COLOR_9  CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_9 )
#define NNP_CANVASCONTAINER_COLOR_10 CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_10)
#define NNP_CANVASCONTAINER_COLOR_11 CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_11) 
#define NNP_CANVASCONTAINER_COLOR_12 CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_12) 
#define NNP_CANVASCONTAINER_COLOR_13 CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_13) 
#define NNP_CANVASCONTAINER_COLOR_14 CONCAT_SYMBOLS(NNP_CANVASCONTAINER_COLORBASE , NNP_COLOR_STAGE_14) 

// Colors for Threads
#define NNP_THREAD_COLORBASE Blue
#define NNP_THREAD_COLOR_1  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_1 )
#define NNP_THREAD_COLOR_2  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_2 )
#define NNP_THREAD_COLOR_3  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_3 )
#define NNP_THREAD_COLOR_4  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_4 )
#define NNP_THREAD_COLOR_5  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_5 )
#define NNP_THREAD_COLOR_6  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_6 )
#define NNP_THREAD_COLOR_7  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_7 )
#define NNP_THREAD_COLOR_8  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_8 )
#define NNP_THREAD_COLOR_9  CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_9 )
#define NNP_THREAD_COLOR_10 CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_10)
#define NNP_THREAD_COLOR_11 CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_11) 
#define NNP_THREAD_COLOR_12 CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_12) 
#define NNP_THREAD_COLOR_13 CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_13) 
#define NNP_THREAD_COLOR_14 CONCAT_SYMBOLS(NNP_THREAD_COLORBASE , NNP_COLOR_STAGE_14) 

// Colors for ObjectGroup
#define NNP_OBJECTGROUP_COLORBASE Yellow
#define NNP_OBJECTGROUP_COLOR_1  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_1 )
#define NNP_OBJECTGROUP_COLOR_2  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_2 )
#define NNP_OBJECTGROUP_COLOR_3  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_3 )
#define NNP_OBJECTGROUP_COLOR_4  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_4 )
#define NNP_OBJECTGROUP_COLOR_5  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_5 )
#define NNP_OBJECTGROUP_COLOR_6  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_6 )
#define NNP_OBJECTGROUP_COLOR_7  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_7 )
#define NNP_OBJECTGROUP_COLOR_8  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_8 )
#define NNP_OBJECTGROUP_COLOR_9  CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_9 )
#define NNP_OBJECTGROUP_COLOR_10 CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_10)
#define NNP_OBJECTGROUP_COLOR_11 CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_11) 
#define NNP_OBJECTGROUP_COLOR_12 CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_12) 
#define NNP_OBJECTGROUP_COLOR_13 CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_13) 
#define NNP_OBJECTGROUP_COLOR_14 CONCAT_SYMBOLS(NNP_OBJECTGROUP_COLORBASE , NNP_COLOR_STAGE_14) 


// Colors for CanvasObject 
#define NNP_OBJECT_COLORBASE Orange
#define NNP_OBJECT_COLOR_1  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_1 )
#define NNP_OBJECT_COLOR_2  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_2 )
#define NNP_OBJECT_COLOR_3  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_3 )
#define NNP_OBJECT_COLOR_4  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_4 )
#define NNP_OBJECT_COLOR_5  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_5 )
#define NNP_OBJECT_COLOR_6  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_6 )
#define NNP_OBJECT_COLOR_7  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_7 )
#define NNP_OBJECT_COLOR_8  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_8 )
#define NNP_OBJECT_COLOR_9  CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_9 )
#define NNP_OBJECT_COLOR_10 CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_10)
#define NNP_OBJECT_COLOR_11 CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_11) 
#define NNP_OBJECT_COLOR_12 CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_12) 
#define NNP_OBJECT_COLOR_13 CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_13) 
#define NNP_OBJECT_COLOR_14 CONCAT_SYMBOLS(NNP_OBJECT_COLORBASE , NNP_COLOR_STAGE_14) 

// Colors for Physics stuff 
#define NNP_PHYSICS_COLORBASE Cyan
#define NNP_PHYSICS_COLOR_1  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_1 )
#define NNP_PHYSICS_COLOR_2  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_2 )
#define NNP_PHYSICS_COLOR_3  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_3 )
#define NNP_PHYSICS_COLOR_4  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_4 )
#define NNP_PHYSICS_COLOR_5  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_5 )
#define NNP_PHYSICS_COLOR_6  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_6 )
#define NNP_PHYSICS_COLOR_7  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_7 )
#define NNP_PHYSICS_COLOR_8  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_8 )
#define NNP_PHYSICS_COLOR_9  CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_9 )
#define NNP_PHYSICS_COLOR_10 CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_10)
#define NNP_PHYSICS_COLOR_11 CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_11) 
#define NNP_PHYSICS_COLOR_12 CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_12) 
#define NNP_PHYSICS_COLOR_13 CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_13) 
#define NNP_PHYSICS_COLOR_14 CONCAT_SYMBOLS(NNP_PHYSICS_COLORBASE , NNP_COLOR_STAGE_14) 
*/

namespace NeuralNet
{
	namespace Profiling
	{
		NEURAL_NET_3_EXPORT void start();
		NEURAL_NET_3_EXPORT uint32_t  saveProfilerFile(const std::string& fileName = "profile.prof");
	}
}